/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.awt.Color;

import java.util.List;
import Entities.Importer;
import Repos.ImporterRepo;

/**
 *
 * @author C.m™ Lap
 */
public class ImportersForm extends javax.swing.JPanel {

    /**
     * Creates new form importersForm
     */
    public ImportersForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        companyNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        countryNameTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        importersTable = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);

        jPanel3.setPreferredSize(new java.awt.Dimension(617, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("اسم الشركه");

        companyNameTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        companyNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("اسم الدوله");

        countryNameTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        countryNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryNameTFActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(companyNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(countryNameTF, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(companyNameTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(countryNameTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        importersTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        importersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "اسم الشركه", "اسم الدوله"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        importersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importersTableMouseClicked(evt);
            }
        });
        importersTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                importersTableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(importersTable);
        importersTable.getTableHeader().setFont(importersTable.getFont());
        importersTable.setRowHeight(importersTable.getFont().getSize() + 12);
        importersTable.setSelectionBackground(Color.GRAY);

        DefaultTableModel model = (DefaultTableModel) importersTable.getModel();
        List<Importer> importers = ImporterRepo.get_all();

        for(Importer importer: importers){
            model.addRow(importer.get_jTable_row());
        }

        jPanel4.add(jScrollPane2);

        jSplitPane1.setRightComponent(jPanel4);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void companyNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameTFActionPerformed

    private void countryNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryNameTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String companyName = companyNameTF.getText();
        String countryName = countryNameTF.getText();
        if (companyName.isEmpty() || countryName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ادخل اسم الدوله واسم الشركه");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) importersTable.getModel();
        if (selectedRow == -1) {

            model.addRow(new String[]{companyName, countryName});
            ImporterRepo.add_new(new Importer(companyName, countryName));

            companyNameTF.setText("");
            countryNameTF.setText("");
        } else {
            int index = (int) model.getValueAt(selectedRow, 0);
            ImporterRepo.update_one(index, new Importer(companyName, countryName));
            model.setValueAt(companyName, selectedRow, 1);
            model.setValueAt(countryName, selectedRow, 2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void importersTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importersTableKeyPressed
        if (selectedRow == -1) {
            return;
        }

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            DefaultTableModel model = (DefaultTableModel) importersTable.getModel();
            ImporterRepo.delete_one((int) model.getValueAt(selectedRow, 0));
            model.removeRow(selectedRow);
            selectedRow = -1;
            importersTable.getSelectionModel().clearSelection();
        }
    }//GEN-LAST:event_importersTableKeyPressed

    private void importersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importersTableMouseClicked
        if (selectedRow == importersTable.getSelectedRow()) {
            importersTable.getSelectionModel().clearSelection();
            companyNameTF.setText("");
            countryNameTF.setText("");
            selectedRow = -1;
            return;
        }
        selectedRow = importersTable.getSelectedRow();

        companyNameTF.setText((String) importersTable.getModel().getValueAt(selectedRow, 1));
        countryNameTF.setText((String) importersTable.getModel().getValueAt(selectedRow, 2));
    }//GEN-LAST:event_importersTableMouseClicked

    private int selectedRow = -1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField companyNameTF;
    private javax.swing.JTextField countryNameTF;
    private javax.swing.JTable importersTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
