/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Color;
import Entities.Product;
import Repos.ProductRepo;
import java.awt.event.KeyEvent;
import java.util.List;

/**
 *
 * @author C.m™ Lap
 */
public class ProductsForm extends javax.swing.JPanel {

    /**
     * Creates new form ProductsForm
     */
    public ProductsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        productNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productSoilCB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("اسم الصنف");

        productNameTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        productNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("نوع التربه");

        productSoilCB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        productSoilCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "طيني", "صحراوي" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productNameTF)
                            .addComponent(productSoilCB, 0, 247, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productSoilCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        productsTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "اسم الصنف", "نوع التربه"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsTableMouseClicked(evt);
            }
        });
        productsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productsTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(productsTable);
        productsTable.getTableHeader().setFont(productsTable.getFont());
        productsTable.setRowHeight(productsTable.getFont().getSize()+12);
        productsTable.setSelectionBackground(Color.GRAY);

        List<Product> products = ProductRepo.get_all();
        DefaultTableModel model = (DefaultTableModel) productsTable.getModel();

        for (Product product: products){
            model.addRow(product.get_jTable_row());
        }

        jPanel2.add(jScrollPane1);

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void productNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String productName = productNameTF.getText();
        String productSolidType = productSoilCB.getSelectedItem().toString();
        if (productName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ادخل اسم الصنف وزوع التربه");
            return;
        }
        if (productsTable.getSelectedRowCount() > 1) {

        } else if (productsTable.getSelectedRowCount() == 1) {
            // update
            int productId = (int) productsTable.getValueAt(productsTable.getSelectedRow(), 0);
            ProductRepo.update_one(productId, new Product(productNameTF.getText(),
                    productSoilCB.getSelectedItem().toString()
            ));
        } else if (productsTable.getSelectedRowCount() == 0) {
            // create
            ProductRepo.add_new(new Product(productName, productSolidType));
        }
        List<Product> products = ProductRepo.get_all();
        ((DefaultTableModel) (productsTable.getModel())).getDataVector().removeAllElements();
        for (Product product : products) {
            ((DefaultTableModel) (productsTable.getModel())).addRow(product.get_jTable_row());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void productsTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productsTableKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_DELETE) {
            return;
        }

        if (productsTable.getSelectedRowCount() > 1) {
            // pulk_delete
            for (int row : productsTable.getSelectedRows()) {
                ProductRepo.delete_one((int) productsTable.getValueAt(row, 0));
            }
        } else if (productsTable.getSelectedRowCount() == 1) {
            // delete_one
            ProductRepo.delete_one((int) productsTable.getValueAt(productsTable.getSelectedRow(), 0));
        } else if (productsTable.getSelectedRowCount() == 0) {
            System.out.println("enta 3bet yabny");
            return;
        }

        List<Product> products = ProductRepo.get_all();
        ((DefaultTableModel) (productsTable.getModel())).getDataVector().removeAllElements();
        for (Product product : products) {
            ((DefaultTableModel) (productsTable.getModel())).addRow(product.get_jTable_row());
        }
    }//GEN-LAST:event_productsTableKeyPressed

    private void productsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsTableMouseClicked
        int row = productsTable.getSelectedRow();
        System.out.println(row);
        if (row == -1) {
            return;
        }
        productNameTF.setText((String) productsTable.getValueAt(row, 1));
        productSoilCB.setSelectedItem(productsTable.getValueAt(row, 2));
    }//GEN-LAST:event_productsTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField productNameTF;
    private javax.swing.JComboBox<String> productSoilCB;
    private javax.swing.JTable productsTable;
    // End of variables declaration//GEN-END:variables
}
